import Languages from "@/types/Localization/Language/Languages";

export const localizationRU: Languages = {
  titlesPage: {
    home: "Главная",
    registration: "Регистрация",
    authorization: "Авторизация",
    persons: "Лиц",
  },
  homePage: {
    header_title: "Войдите Для Просмотра",
  },
  headerPage: {
    link_home: "Главная",
    exit: "Выход",
  },
  userPage: {
    registration: "Регистрация",
    authorization: "Авторизация",
    name: "Имя",
    nameError: "Заполняйте Имя",
    surname: "Фамилия",
    surnameError: "Заполняйте Фамилия",
    phone: "Телефон",
    phoneError: "Заполняйте Телефон",
    email: "Почта",
    emailError: "Заполняйте Почта",
    password: "Пароль",
    passwordError: "Заполняйте Пароль",
    confirmPassword: "Повторяйте Пароль",
    confirmPasswordError: "Пароль Не Корректно",
    send: "Отправить",
  },
  personPage: {
    title_table: "Таблица Лиц",
    show_table: "Показ",
    sort_table: "Сортировать",
    to_sort_table: "До",
    id: "ИД",
    to_sort_up: "Вверх",
    to_sort_down: "Вниз",
    search: "Поиск",
    update: "Изменить",
    delete: "Удалить",
    delete_text_confirm: "Вы хотите удалить?",
    back: "Назад",
    next: "Вперед",
    add_person: "Добавить Лиц",
    create: "Создать",
    close: "Закрыть",
    save: "Сохранять",
  },
  alertPage: {
    empty_info: "Пустая информация",
    success_login: "Успех Войти",
    error_login: "Ошибка Bхода",
    success_register: "Успех Регистрация",
    error_register: "Ошибка Регистрация",
    error_email: "Ошибка Почта",
    success_exit: "Успех Выход",
    success_added: "Успех Добавлен",
    success_updated: "Успех Измемен",
    success_deleted: "Успех Удален",
  },
};
