import Languages from "@/types/Localization/Language/Languages";

export const localizationEN: Languages = {
  titlesPage: {
    home: "Home",
    registration: "Registration",
    authorization: "Login",
    persons: "Persons",
  },
  homePage: {
    header_title: "Login To View",
  },
  headerPage: {
    link_home: "Home",
    exit: "Exit",
  },
  userPage: {
    registration: "Registration",
    authorization: "Login",
    name: "Name",
    nameError: "Fill in Name",
    surname: "Surname",
    surnameError: "Fill in Surname",
    phone: "Phone",
    phoneError: "Fill in Phone",
    email: "Email",
    emailError: "Fill in Mail",
    password: "Password",
    passwordError: "Fill in Password",
    confirmPassword: "Confirm Password",
    confirmPasswordError: "Password Not Correct",
    send: "Send",
  },
  personPage: {
    title_table: "Persons Table",
    show_table: "Show",
    sort_table: "Sort",
    to_sort_table: "To",
    id: "ID",
    to_sort_up: "Up",
    to_sort_down: "Down",
    search: "Search",
    update: "Update",
    delete: "Delete",
    delete_text_confirm: "Do you want to delete?",
    back: "Back",
    next: "Next",
    add_person: "Add Person",
    create: "Create",
    close: "Close",
    save: "Save",
  },
  alertPage: {
    empty_info: "Empty Info",
    success_login: "Success Login",
    error_login: "Error Login",
    success_register: "Success Register",
    error_register: "Error Register",
    error_email: "Error Email",
    success_exit: "Success Exit",
    success_added: "Success Added",
    success_updated: "Success Updated",
    success_deleted: "Success Deleted",
  },
};
