export enum MutationTypes {
  M_REGISTER_NEW_USER = "M_REGISTER_NEW_USER",
  M_USERS_IN_COOKI = "M_USERS_IN_COOKI",
  M_CHECK_LOGIN = "M_CHECK_LOGIN",
  M_AUTOLOGIN = "M_AUTOLOGIN",
  M_LOGOUT = "M_LOGOUT",
}
