export enum ActionTypes {
  A_REGISTER_NEW_USER = "A_REGISTER_NEW_USER",
  A_USERS_IN_COOKI = "A_USERS_IN_COOKI",
  A_CHECK_LOGIN = "A_CHECK_LOGIN",
  A_AUTOLOGIN = "A_AUTOLOGIN",
  A_LOGOUT = "A_LOGOUT",
}
